### PR TITLE
Update subdomain.yml

### PR DESCRIPTION
**Pull request by ALBINPRAVEEN**
added albinpraveen subdomain in cname section

### CODE REVIEW

**Comment by DennisKidman** [comment]
Hi! I have added the record... but still can't access the website; https://www.whatsmydns.net/#CNAME/albinpraveen.io.day

Have you added the domain in the Vercel config?

**Comment by pythoniaweb** [comment]
its ssl problem cloudflare and varcel is 99% not compilable

**Comment by pythoniaweb** [comment]
its happened by ssl so yeah its his problem site is accessable with http but he set up only https

**Comment by pythoniaweb** [comment]
@ALBINPRAVEEN @DennisKidman

**Comment by ALBINPRAVEEN** [comment]
I would then add ns in it

**Comment by ALBINPRAVEEN** [comment]
Can I add txt for this domain

**Comment by DennisKidman** [comment]
yeah you can

**Comment by ALBINPRAVEEN** [comment]
_vercel
Value:vc-domain-verify=albinpraveen.io.day,87b46e12382915f9821a

**Comment by ALBINPRAVEEN** [comment]
Can u add this txt

**Comment by DennisKidman** [comment]
https://www.whatsmydns.net/#TXT/albinpraveen.io.day correct?

**Comment by DennisKidman** [comment]
https://www.whatsmydns.net/#TXT/_vercel.io.day I have added the record... you can check here

**Comment by ALBINPRAVEEN** [comment]
Thanks

**Comment by ALBINPRAVEEN** [comment]
Ys it's correct thnkz

**Pull request merged**
