### PR TITLE
added subdomain entry "alberto"

### PR DESCRIPTION
**Pull request by ksdhall**

### CODE REVIEW

**Comment by DennisKidman** [comment]
Hi, added the record!

**Comment by DennisKidman** [comment]
Error 1014
CNAME Cross-User Banned

You might want to check this...

**Comment by ksdhall** [comment]
Thank you @DennisKidman 
I've made some changes to the CNAME pointing, and I hope it works correctly now. Previously, I had set up a Cloudflare tunnel to my docker subnet, but it didn't work as expected. 
Sorry for any inconvenience caused. I'm still in the process of learning how to properly map external domains.

**Comment by DennisKidman** [comment]
No problem, mate... Let me know if you encounter any problem

**Pull request merged**
