### PR TITLE
Update subdomain.yml

### PR DESCRIPTION
**Pull request by charliebunt**

### CODE REVIEW

**Comment by DennisKidman** [comment]
Added the record with no proxy... You need to enforce HTTPS manually on Github pages config

**Comment by charliebunt** [comment]
Thanks 😊

**Comment by DennisKidman** [comment]
Hey, may I know what the website will be used for and what content are you showing?

**Comment by DennisKidman** [comment]
Hey there! Sorry to bother you, but I was wondering if you could let me know what the website is going to be used for. Also, just a quick heads-up, we have some rules around here that we need to follow. Our subdomains aren't allowed to host politically sensitive, violent, pornographic, or other illegal content.

I've temporarily disabled the domain for now. But no worries, I'll be happy to enable it later once I have a better idea of what you're working on. Could you please share with me a strong description of your project or site?

**Comment by charliebunt** [comment]
Sure thing. It is a tribute site for a marionette theatre I ran many years
ago and it will contain a link to Spotify and to blurb. We toured to over
300 institutions including festivals and schools by private and public as
well as disabled young and old in the 90s so this is the site I created not
long after . It is static because the old store etc is no longer and it is
unresponsive for mobile phones but I want it to just stand as it did all
those years ago as a tribute and point of reference for the music on
Spotify for toybox puppet theatre . I am co creator my name is Charlotte
Bunt. Do you think this domain of yours will be available for a long time ?

**Comment by charliebunt** [comment]
https://open.spotify.com/artist/4R0pgyrJNfmBsRQEslkg3o


That is me CHARLOTTE BUNT

**Comment by charliebunt** [comment]
And actually I really need someone I can depend on for the sake of this
tribute site because I plan on linking it as a reference guide.

Our music is actually available at the National Library of Australia for
those wanting to listen for free because we are part of history in
education.

This is a tribute site , We no longer run puppet shows.

**Comment by DennisKidman** [comment]
Got it, website re-enabled! Let me know if you need anything else.

**Comment by charliebunt** [comment]
I am happy to register another subdomain if you do not want it on your
site, Please let me know as probably I will have to register a paid domain
to keep it secure but its just I am 62 years old ! I need a place where the
tribute site will remain long after I'm dead

**Comment by charliebunt** [comment]
Thank you!

**Comment by DennisKidman** [comment]
No worries! We'll definitely keep the subdomain up and running long-term, so you don't need to worry about a thing. It'll be secure and available for years to come, so you can rest easy knowing it'll stick around even after you're gone. No need to register a paid domain...

**Comment by charliebunt** [comment]
Great, thanks! People around 29 years of age to 34 will hopefully find it
and remember the shows as young kids.

**Pull request merged**
