### PR TITLE
Update subdomain.yml

### PR DESCRIPTION
**Pull request by cauvang32**

### CODE REVIEW

**Comment by DennisKidman** [comment]
Hi, record added... https://www.whatsmydns.net/#NS/cauvang28.io.day

**Comment by cauvang32** [comment]
thank you!

**Comment by DennisKidman** [comment]
is the domain working? @cauvang32

**Comment by cauvang32** [comment]
It work thank you ! @DennisKidman

**Comment by DennisKidman** [comment]
No problem!

**Pull request merged**
