### PR TITLE
Update subdomain.yml / 03/20

### PR DESCRIPTION
**Pull request by adolf-commerce**
Please add the NS record of xyz.wf at the same time,Thank you.

### CODE REVIEW

**Comment by DennisKidman** [comment]
Do you mean that you also want to register biz.io.day?

I have added the record;

https://www.nslookup.io/domains/biz.xyz.wf/dns-records/

**Comment by adolphin-CEO** [comment]
Yes,I want to register biz.io.day,thank you.

**Comment by DennisKidman** [comment]
https://www.nslookup.io/domains/biz.io.day/dns-records/

Added

**Comment by adolphin-CEO** [comment]
I really appreciate it.

**Comment by DennisKidman** [comment]
No problem

**Comment by DennisKidman** [comment]
Hey check out our new website https://dual.my/

**Pull request closed without merging**
