### PR TITLE
Updated subdomain.yml

### PR DESCRIPTION
**Pull request by hatsign**

### CODE REVIEW

**Comment by DennisKidman** [comment]
Sorry but I don't think using Cloudflare for io.day subdomain is possible

**Comment by hatsign** [comment]
I know that cloudflare doesn't allow adding domains as subdomains but if you can setup the records that's not a problem for me I've got a trick to make cloudflare recognize subdomain as domain

**Comment by DennisKidman** [comment]
Alright, records added!
https://www.whatsmydns.net/#NS/cloner.io.day

**Comment by hatsign** [comment]
thanks it's working.

**Pull request merged**
