### PR TITLE
Update subdomain.yml

### PR DESCRIPTION
**Pull request by Hutotpn**

### CODE REVIEW

**Comment by DennisKidman** [comment]
Hi! I have added the record https://www.whatsmydns.net/#CNAME/huto-comsci-test.io.day

If you need TXT verification for Vercel just let me know

**Comment by Hutotpn** [comment]
No, thank you

**Comment by Hutotpn** [comment]
> Hi! I have added the record https://www.whatsmydns.net/#CNAME/huto-comsci-test.io.day @Hutotpn
> 
> If you need TXT verification for Vercel just let me know

No, thank you

Thanks for your time and help

**Comment by Hutotpn** [comment]
I've got an error @DennisKidman 
It says "io.day or one of its subdomains is already managed by Netlify DNS on another team."


eb499c31-22d8-4178-98ca-860ff9b479bb

**Comment by DennisKidman** [comment]
Hi, I think you need to verify the domain ownership
https://answers.netlify.com/t/support-guide-another-site-is-using-this-domain-verifying-domain-ownership-for-netlify-production-domain/13765

I will try add the TXT record

**Comment by Hutotpn** [comment]
Could you please change the TXT value to `verified-for-netlify ticket#138808` @DennisKidman

**Comment by Hutotpn** [comment]
Could you please change the TXT value to verified-for-netlify ticket#138808
@DennisKidman <https://github.com/DennisKidman>

**Comment by Hutotpn** [comment]
Could you please change the TXT value to `verified-for-netlify ticket#138808` @DennisKidman

**Comment by DennisKidman** [comment]
Hi, I have updated the record @Hutotpn 
https://www.whatsmydns.net/#TXT/huto-comsci-test.io.day

**Comment by Hutotpn** [comment]
Thank you for your assistance.

**Pull request closed without merging**
