### PR TITLE
Update subdomain.yml

### PR DESCRIPTION
**Pull request by Stevemoretz**
Thanks in advance, this is my resume.

### CODE REVIEW

**Comment by DennisKidman** [comment]
Hi, sorry for keeping you waiting... I have added the record!

**Comment by DennisKidman** [comment]
Hi is the domain working?

**Comment by Stevemoretz** [comment]
Thank you Dennis, I don't understand why it gives a 404 maybe I also need to change some settings in my github account, Stevemoretz.github.io works but Stevemoretz.io.day gives a 404 I thought a cname record was enough for this to work

**Comment by Stevemoretz** [comment]
> Hi, I think you need to configure stevemoretz.io.day in your GitHub Pages settings in order for it to work. You can take a look at my Imgur image for an example: https://imgur.com/a/n9BUgMY. If you add stevemoretz.io.day to your project, it should work.

Thank you so much it is working now :)

**Comment by DennisKidman** [comment]
Great to hear that. No problem, mate.

**Pull request merged**
