### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Berlin-Daemon**

### CODE REVIEW

**Comment by DennisKidman** [comment]
Is it possible to add Cloudflare for io.day subdomain?

**Comment by Berlin-Daemon** [comment]
added to cloudflare 2 days😀

**Comment by DennisKidman** [comment]
https://www.whatsmydns.net/#NS/ltd.io.day

Ok records added @Berlin-Daemon

**Comment by Berlin-Daemon** [comment]
thank u

**Comment by DennisKidman** [comment]
no problem

**Pull request closed without merging**
