### PR TITLE
Update subdomain.yml

### PR DESCRIPTION
**Pull request by sinaparsa90**

### CODE REVIEW

**Comment by DennisKidman** [comment]
Hello, is this correct?

   -name: sinacode
    value: sinacode.gw.to
    proxy: true
    
    I can't access http://sinacode.gw.to/

**Comment by DennisKidman** [comment]
Record added...

https://www.whatsmydns.net/#A/sinacode.io.day

https://sinacode.io.day/

Error code 521

**Comment by sinaparsa90** [comment]
Dear Dennis
Hi the host : sinacode.gw.to is the ip of my VPS and if you ping it , it shows that ip. I have a vpn server on it which I want to use it on a subdomain with a ssl. could you help me wether I use A record or Cname?
Thank you Best regards

    On Tuesday, March 7, 2023 at 05:04:40 PM GMT+3:30, DennisKidman ***@***.***> wrote:  
 
 


Hello, is this correct?

-name: sinacode
value: sinacode.gw.to
proxy: true
I can't access http://sinacode.gw.to/

**Comment by DennisKidman** [comment]
Yes, I can access your website... But I think we can use A records for this. But I need your VPS IP address (Ipv4)

http://sinacode.gw.to/

**Comment by sinaparsa90** [comment]
you colud ping sinacode.gw.to which shows :  91.107.156.81 that is my VPS Ipv4.I already made an A record in my server with sinait.io.day with this Ip.
    On Tuesday, March 7, 2023 at 09:51:55 PM GMT+3:30, DennisKidman ***@***.***> wrote:  
 
 


Yes, I can access your website... But I think we can use A records for this. But I need your VPS IP address (Ipv4)

http://sinacode.gw.to/

**Comment by sinaparsa90** [comment]
91.107.156.81  is my VPS Ipv4.
I already made an A record in my server that is sinait.io.day with this IP.

**Comment by DennisKidman** [comment]
It's not sinait.io.day... What you commit in the subdomain.yml is "sinacode.io.day"

**Comment by DennisKidman** [comment]
I think we can use the CNAME record instead...

This is tutorial I find which may be beneficial;
https://www.hostinger.my/tutorials/error-521#:~:text=If%20your%20website%20is%20showing,software%20that%20blocks%20Cloudflare%20IPs.

**Comment by DennisKidman** [comment]
Confirm [Cloudflare IP addresses](https://www.cloudflare.com/ips) are not blocked or rate limited
Allow all [Cloudflare IP ranges](https://www.cloudflare.com/ips) in your origin web server's firewall or other security software

**Comment by sinaparsa90** [comment]
I added the ips of clouflare but the problem with CNAME is still remained
iptables

**Comment by DennisKidman** [comment]
Hmm, I guess this problem is related to Cloudflare. I have another domain as well... Do you want to use a domain called "sinacode.app.mq"?

**Comment by DennisKidman** [comment]
https://sinacode.app.mq/

**Comment by DennisKidman** [comment]
Ok, it's working now https://sinacode.io.day/

**Comment by DennisKidman** [comment]
https://sinacode.app.mq/

This website work... If you want an app.mq domain. It will be hard to implement your io.day domain because the current encryption is "full" instead of "flexible"

**Comment by sinaparsa90** [comment]
https://sinacode.app.mq/ this is ok but I want to set an A record with my vps IP address on it could you do that?
VPS IP: 91.107.156.81

**Comment by DennisKidman** [comment]
When I add A record, I will get this response; Web server is down Error code 521

I think it's better to use CNAME

**Comment by sinaparsa90** [comment]
I believe its because I didn't add an A record in my server before.
I now added that 
Plz check it now if that error gone?
Screenshot_20230308-181510_Chrome

**Comment by DennisKidman** [comment]
It's not... its looks like maybe Hetzner is using Cloudflare by default. Serious question why don't you just use CNAME? I can access your website through CNAME

**Comment by sinaparsa90** [comment]
I need to use my other panels (such as xui vpn server) on this host(sinacode.app.mq) which without A record its not possible. Is it? 
Yes both ipv4 and ipv6 is provided by hetzner

**Comment by DennisKidman** [comment]
You can try posting your IPv6 here. I don't understand... Your website "https://sinacode.app.mq/" is accessible even with CNAME

**Comment by sinaparsa90** [comment]
Is there any possibility to remove ssl from sinacode.app.mq
Also you can find my ipv6 in below image:
2a01:4f8:1c1b:22af::1

**Comment by DennisKidman** [comment]
I'm sorry without SSL, your website will be inaccessible. This is because (.day) domain used HSTS by default

**Pull request closed without merging**
