### PR TITLE
Replace DNS Server

### PR DESCRIPTION
**Pull request by Berlin-Daemon**
Thank u so much.

### CODE REVIEW

**Comment by DennisKidman** [comment]
hi sorry for keep you waiting; Records updated https://www.whatsmydns.net/#NS/ltd.io.day

**Comment by Berlin-Daemon** [comment]
cheers bro

**Comment by DennisKidman** [comment]
Is the domain working? @Berlin-Daemon

**Comment by DennisKidman** [comment]
Ok no problem

**Pull request merged**
