### PR TITLE
Add: gravity.io.day

### PR DESCRIPTION
**Pull request by HarisETH**
This is for a personal project.

### CODE REVIEW

**Comment by DennisKidman** [comment]
Hi, are you using the NS or the CNAME records? I will try to use the CNAME records first

**Review by DennisKidman — APPROVED** [review]

**Comment by DennisKidman** [comment]
Added CNAME please... check vercel config

**Comment by HarisETH** [comment]
There is no changes in Vercel

**Comment by HarisETH** [comment]
It states 'Another Vercel account is using this domain. Please set the following TXT record on _vercel.io.day to use gravity.io.day in this project. Once the verification is completed and the domain is successfully configured, the TXT record can be removed.'

**Comment by HarisETH** [comment]
image

**Comment by DennisKidman** [comment]
Hi, I have added the TXT records

**Comment by DennisKidman** [comment]
Can you send me the value for the TXT value? And also, do you know what the current status is?

**Comment by DennisKidman** [comment]
https://www.whatsmydns.net/#TXT/_vercel.io.day

is the value correct?

**Comment by HarisETH** [comment]
Thank you so much ! the domain is working .

**Comment by DennisKidman** [comment]
I changed the value of the CNAME to https://usegravitytool.vercel.app/

I think this is because cname.vercel-dns.com value is already taken

**Comment by DennisKidman** [comment]
Good to know that

I changed the value of the CNAME to https://usegravitytool.vercel.app/

I think this is because the cname.vercel-dns.com value is already taken

**Pull request merged**
